In [1]:
import numpy as np

# 1. Create Arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])
print("Array 1:", arr1)
print("Array 2:", arr2)

# 2. Array Addition
print("\nAddition:", arr1 + arr2)

# 3. Array Subtraction
print("Subtraction:", arr2 - arr1)

# 4. Element-wise Multiplication
print("Multiplication:", arr1 * arr2)

# 5. Element-wise Division
print("Division:", arr2 / arr1)

# 6. Scalar Operations (Multiply all elements by 2)
print("\nArray 1 multiplied by 2:", arr1 * 2)

# 7. Mathematical Functions
print("\nSquare root of Array 1:", np.sqrt(arr1))
print("Exponent of Array 1:", np.exp(arr1))
print("Log of Array 1:", np.log(arr1))

# 8. Statistics on Arrays
print("\nSum of Array 1:", np.sum(arr1))
print("Mean of Array 1:", np.mean(arr1))
print("Max value in Array 2:", np.max(arr2))
print("Min value in Array 2:", np.min(arr2))

# 9. Reshaping Arrays
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("\nOriginal Matrix:\n", matrix)
reshaped = matrix.reshape(3, 2)
print("Reshaped Matrix (3x2):\n", reshaped)

# 10. Matrix Multiplication
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
print("\nMatrix 1:\n", mat1)
print("Matrix 2:\n", mat2)
print("Matrix Multiplication:\n", np.dot(mat1, mat2))


Array 1: [1 2 3 4 5]
Array 2: [10 20 30 40 50]

Addition: [11 22 33 44 55]
Subtraction: [ 9 18 27 36 45]
Multiplication: [ 10  40  90 160 250]
Division: [10. 10. 10. 10. 10.]

Array 1 multiplied by 2: [ 2  4  6  8 10]

Square root of Array 1: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponent of Array 1: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Log of Array 1: [0.         0.69314718 1.09861229 1.38629436 1.60943791]

Sum of Array 1: 15
Mean of Array 1: 3.0
Max value in Array 2: 50
Min value in Array 2: 10

Original Matrix:
 [[1 2 3]
 [4 5 6]]
Reshaped Matrix (3x2):
 [[1 2]
 [3 4]
 [5 6]]

Matrix 1:
 [[1 2]
 [3 4]]
Matrix 2:
 [[5 6]
 [7 8]]
Matrix Multiplication:
 [[19 22]
 [43 50]]
